export const ADD_CONTACT = "ADD_CONTACT";
export const DElETE_CONTACT = "DELETE_CONTACT";
export const SET_CONTACT = "SET_CONTACT";
export const UPDATE_CONTACT = "UPDATE_CONTACT";
export const FILTER_CONTACT = "FILTER_CONTACT";
export const CLEAR_CONTACT = "CLEAR_CONTACT";
export const SET_ALERT = "SET_ALERT";
export const REMOVE_CONTACT = "REMOVE_CONTACT";
